services: 
  webserver:
    container_name: webserver
    image: nginx:latest
    restart: always
    volumes:
      - ./config/nginx/templates:/etc/nginx/templates
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/dhparam/:/etc/ssl/certs
      - uwsgi-socket:/app/uwsgi/:ro
      - static-files:/app/static:ro
      - certbot-etc:/etc/letsencrypt:ro
      - certbot-var:/var/lib/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - pybossa-server
      - pybossa-worker
      - pybossa-scheduler
  
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - static-files:/var/www/certbot
    depends_on:
      - webserver
    command: ["certonly", "--rsa-key-size", "2048", "--webroot", "--webroot-path=/var/www/certbot", "--force-renewal", "--email", "dev@citizenscience.ch", "--agree-tos", "--no-eff-email", "-d", "pybossa-testing.citizenscience.ch",  "-d", "www.pybossa-testing.citizenscience.ch"]

volumes:
  certbot-etc:
  certbot-var:
