services:
  pybossa-server:
    networks:
      - postgres
    env_file:
      - ./config/env/.env.dev

  pybossa-worker:
    networks:
      - postgres
    env_file:
      - ./config/env/.env.dev

  pybossa-scheduler:
    networks:
      - postgres
    env_file:
      - ./config/env/.env.dev
  
  webserver:
    env_file:
      - ./config/env/.env.dev
    networks:
      - web

networks:
  web:
    name: pybossa-web-net
  postgres:
    name: pybossa-postgres-net
    external: true
  
  