services:
#  web:
#    container_name: nginx
#    image: nginx:latest
#    restart: unless-stopped
#    volumes:
#    - config/nginx/templates:/etc/nginx/templates
#    ports:
#    - "8080:80"
#    environment:
#    - NGINX_HOST=foobar.com
#    - NGINX_PORT=80

  redis-master:
    container_name: redis-master
    image: redis:latest
    # command: ["redis-server", "/usr/local/etc/redis/master.conf"]
    volumes:
      - ./config/redis-master:/usr/local/etc/redis
    ports:
      - "6379:6379"
    networks:
      - redis
  
  redis-replica:
    container_name: redis-replica
    image: redis:latest
    command: ["redis-server", "/usr/local/etc/redis/replica.conf"]
    volumes:
      - ./config/redis-replica:/usr/local/etc/redis
    ports:
      - "6380:6379"
    depends_on:
      - redis-master
    networks:
      - redis

  redis-sentinel:
    container_name: redis-sentinel
    image: redis:latest
    command: ["redis-server", "/usr/local/etc/redis/sentinel.conf",  "--sentinel"]
    volumes:
      - ./config/redis-sentinel:/usr/local/etc/redis
    ports:
      - "26379:26379"
    depends_on:
      - redis-master
      - redis-replica
    networks:
      - redis
  
  pybossa-master:
    container_name: pybossa-master
    image: pybossa:latest
    build: 
      context: ./
      dockerfile: ./apps/pybossa/Dockerfile
    networks:
      - backend
      - redis
    external_links:
      - postgres
    depends_on:
      - redis-master
      - redis-replica
      - redis-sentinel
    ports:
      - "8080:8080"
    env_file:
      - .env
  
  pybossa-worker:
    container_name: pybossa-worker
    image: pybossa:latest
    networks:
      - backend
      - redis
    external_links:
      - postgres
    depends_on:
      - redis-master
      - redis-replica
      - redis-sentinel
    env_file:
      - .env
    command: ["rqscheduler", "--host", "redis-master", "--port", "6379", "--interval", "60" , "--db",  "0"]
  
  pybossa-scheduler:
    container_name: pybossa-scheduler
    image: pybossa:latest
    environment:
      DB_INIT: True
    networks:
      - backend
      - redis
    external_links:
      - postgres
    depends_on:
      - redis-master
      - redis-replica
      - redis-sentinel
    env_file:
      - .env
    command: ["python", "app_context_rqworker.py", "scheduled_jobs", "super", "high", "medium", "low" , "email",  "maintenance"]
  
  c3s:
    container_name: c3s
    image: c3s-lab-client:latest
    build: 
      context: ./
      dockerfile: ./apps/c3s-lab-client/Dockerfile
    ports:
    - "8081:80"

networks:
  backend:
    name: pybossa-postgres-net
    external: true
  redis:

      
#external_links: 
# - database:postgresql

#configs:
#  redis-config:
#    external: true
#  sentinel-config:
#    external: true