services:
  redis-master:
    container_name: redis-master
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - redis
  
  redis-replica:
    container_name: redis-replica
    restart: always
    image: redis:replica
    build: 
      context: ./
      dockerfile: ./docker/redis/Dockerfile
      target: redis-replica
    depends_on:
      - redis-master
    networks:
      - redis

  redis-sentinel:
    container_name: redis-sentinel
    image: redis:sentinel
    restart: always
    build: 
      context: ./
      dockerfile: ./docker/redis/Dockerfile
      target: redis-sentinel
    ports:
      - "26379:26379"
    depends_on:
      - redis-master
      - redis-replica
    networks:
      - redis
  
  pybossa-server:
    container_name: pybossa-server
    restart: unless-stopped
    image: pybossa:server
    volumes:
      - ./uploads:/app/uploads
      - static-files:/app/pybossa/pybossa/themes/default/static
      - uwsgi-socket:/tmp/
    build: 
      context: ./
      dockerfile: ./docker/pybossa/Dockerfile
      target: pybossa-server
    networks:
      - redis
      - backend
    depends_on:
      - redis-master
      - redis-replica
      - redis-sentinel
      - pybossa-scheduler
    env_file:
      - ./config/env/.env.secrets
      - ./config/env/.env.mail
  
  pybossa-worker:
    container_name: pybossa-worker
    restart: unless-stopped
    image: pybossa:worker
    build: 
      context: ./
      dockerfile: ./docker/pybossa/Dockerfile
      target: pybossa-worker
    networks:
      - redis
      - backend
    depends_on:
      - redis-master
      - redis-replica
      - redis-sentinel
      - pybossa-scheduler
    env_file:
      - ./config/env/.env.secrets
      - ./config/env/.env.mail
  
  pybossa-scheduler:
    container_name: pybossa-scheduler
    restart: unless-stopped
    image: pybossa:scheduler
    build: 
      context: ./
      dockerfile: ./docker/pybossa/Dockerfile
      target: pybossa-scheduler
    networks:
      - redis
      - backend
    depends_on:
      - redis-master
      - redis-replica
      - redis-sentinel
    env_file:
      - ./config/env/.env.secrets
      - ./config/env/.env.mail

  webserver:
    container_name: webserver
    image: nginx:latest
    restart: always
    volumes:
      - ./config/nginx/templates:/etc/nginx/templates
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - uwsgi-socket:/app/uwsgi/:ro
      - static-files:/app/static:ro
    depends_on:
      - pybossa-server
      - pybossa-worker
      - pybossa-scheduler

networks:  
  redis:
  backend:
  
volumes:
  static-files:
  uwsgi-socket:

