services: 
#  web:
#    container_name: nginx
#    image: nginx:latest
#    restart: unless-stopped
#    volumes:
#    - config/nginx/templates:/etc/nginx/templates
#    ports:
#    - "8080:80"
#    environment:
#    - NGINX_HOST=foobar.com
#    - NGINX_PORT=80

  pybossa-master:
    env_file:
      - ./config/env/.env.test
      - ./config/env/.env.secrets
  
  pybossa-worker:
    env_file:
      - ./config/env/.env.test
      - ./config/env/.env.secrets

  pybossa-scheduler:
    env_file:
      - ./config/env/.env.test
      - ./config/env/.env.secrets
