services:
  redis-master:
    container_name: redis-master
    image: redis:latest
    # command: ["redis-server", "/usr/local/etc/redis/master.conf"]
    volumes:
      - ./config/redis-master:/usr/local/etc/redis
    ports:
      - "6379:6379"
    networks:
      - redis
  
  redis-replica:
    container_name: redis-replica
    image: redis:latest
    command: ["redis-server", "/usr/local/etc/redis/replica.conf"]
    volumes:
      - ./config/redis-replica:/usr/local/etc/redis
    ports:
      - "6380:6379"
    depends_on:
      - redis-master
    networks:
      - redis

  redis-sentinel:
    container_name: redis-sentinel
    image: redis:latest
    command: ["redis-server", "/usr/local/etc/redis/sentinel.conf",  "--sentinel"]
    volumes:
      - ./config/redis-sentinel:/usr/local/etc/redis
    ports:
      - "26379:26379"
    depends_on:
      - redis-master
      - redis-replica
    networks:
      - redis
  
  pybossa-server:
    container_name: pybossa-server
    image: pybossa:server
    volumes:
      - ./uploads:/app/uploads
      - static-files:/app/pybossa/pybossa/themes/default/static
      - uwsgi-socket:/tmp/
      # - type: volume
      #   source: uploads-nfs
      #   target: /app/uploads
      #   volume:
      #     nocopy: true
    build: 
      context: ./
      dockerfile: ./docker/pybossa/Dockerfile
      target: pybossa-server
    networks:
      - redis
      - backend
    depends_on:
      - redis-master
      - redis-replica
      - redis-sentinel
      - pybossa-scheduler
    env_file:
      - ./config/env/.env.secrets
      - ./config/env/.env.mail
  
  pybossa-worker:
    container_name: pybossa-worker
    image: pybossa:worker
    build: 
      context: ./
      dockerfile: ./docker/pybossa/Dockerfile
      target: pybossa-worker
    networks:
      - redis
      - backend
    depends_on:
      - redis-master
      - redis-replica
      - redis-sentinel
      - pybossa-scheduler
    env_file:
      - ./config/env/.env.secrets
      - ./config/env/.env.mail
  
  pybossa-scheduler:
    container_name: pybossa-scheduler
    image: pybossa:scheduler
    build: 
      context: ./
      dockerfile: ./docker/pybossa/Dockerfile
      target: pybossa-scheduler
    networks:
      - redis
      - backend
    depends_on:
      - redis-master
      - redis-replica
      - redis-sentinel
    env_file:
      - ./config/env/.env.secrets
      - ./config/env/.env.mail

networks:  
  redis:
  backend:

volumes:
  static-files:
  uwsgi-socket:
  # uploads-nfs:
  #   driver_opts:
  #     type: "nfs"
  #     o: "addr=db-master-testing.c3s.internal,nolock,soft,rw"
  #     device: ":/nfs/uploads"

