services: 
  pybossa-server:
    env_file:
      - ./config/env/.env.test
      - ./config/env/.env.secrets
      - ./config/env/.env.mail
  
  pybossa-worker:
    env_file:
      - ./config/env/.env.test
      - ./config/env/.env.secrets
      - ./config/env/.env.mail

  pybossa-scheduler:
    env_file:
      - ./config/env/.env.test
      - ./config/env/.env.secrets
      - ./config/env/.env.mail

  webserver:
    env_file:
      - ./config/env/.env.test
  
  certbot:
    env_file:
      - ./config/env/.env.test